#!/bin/sh
set -eu
SOURCE_ROOT="https://raw.githubusercontent.com/SubmitterTech/quran-tft/main/app/src/assets/pictures"
TARGET_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
curl -fL "$SOURCE_ROOT/4.jpg" -o "$TARGET_DIR/4.jpg"
curl -fL "$SOURCE_ROOT/5.jpg" -o "$TARGET_DIR/5.jpg"
curl -fL "$SOURCE_ROOT/9.jpg" -o "$TARGET_DIR/9.jpg"
curl -fL "$SOURCE_ROOT/10.jpg" -o "$TARGET_DIR/10.jpg"
curl -fL "$SOURCE_ROOT/13.jpg" -o "$TARGET_DIR/13.jpg"
curl -fL "$SOURCE_ROOT/14.jpg" -o "$TARGET_DIR/14.jpg"
curl -fL "$SOURCE_ROOT/15.jpg" -o "$TARGET_DIR/15.jpg"
curl -fL "$SOURCE_ROOT/16.jpg" -o "$TARGET_DIR/16.jpg"
curl -fL "$SOURCE_ROOT/17.jpg" -o "$TARGET_DIR/17.jpg"
curl -fL "$SOURCE_ROOT/18.jpg" -o "$TARGET_DIR/18.jpg"
curl -fL "$SOURCE_ROOT/19.jpg" -o "$TARGET_DIR/19.jpg"
curl -fL "$SOURCE_ROOT/20.jpg" -o "$TARGET_DIR/20.jpg"
curl -fL "$SOURCE_ROOT/21.jpg" -o "$TARGET_DIR/21.jpg"
curl -fL "$SOURCE_ROOT/22.jpg" -o "$TARGET_DIR/22.jpg"
curl -fL "$SOURCE_ROOT/22-1.jpg" -o "$TARGET_DIR/22-1.jpg"
curl -fL "$SOURCE_ROOT/22-2.jpg" -o "$TARGET_DIR/22-2.jpg"
curl -fL "$SOURCE_ROOT/22-3.jpg" -o "$TARGET_DIR/22-3.jpg"
curl -fL "$SOURCE_ROOT/22-4.jpg" -o "$TARGET_DIR/22-4.jpg"
curl -fL "$SOURCE_ROOT/22-5.jpg" -o "$TARGET_DIR/22-5.jpg"
curl -fL "$SOURCE_ROOT/22-6.jpg" -o "$TARGET_DIR/22-6.jpg"
curl -fL "$SOURCE_ROOT/22-7.jpg" -o "$TARGET_DIR/22-7.jpg"
curl -fL "$SOURCE_ROOT/23.jpg" -o "$TARGET_DIR/23.jpg"
curl -fL "$SOURCE_ROOT/24.jpg" -o "$TARGET_DIR/24.jpg"
curl -fL "$SOURCE_ROOT/25.jpg" -o "$TARGET_DIR/25.jpg"
curl -fL "$SOURCE_ROOT/26.jpg" -o "$TARGET_DIR/26.jpg"
curl -fL "$SOURCE_ROOT/27.jpg" -o "$TARGET_DIR/27.jpg"
echo "Tamamlandi."
